### ISSUE TITLE
404 not found on the images loaded via proxy

### ISSUE THREAD

**Issue by mandazi** [brcontainer/html2canvas-csharp-proxy#1]
I have implemented a basic setup of this and whenever I run html2canvas it tries to loads images that look like this:

/js/images/9198119e5333b5dcfcc353d3abb8eb1205c71e33

When I try to go directly to the path above I get this error:

HTTP Error 404.17 - Not Found
The requested content appears to be script and will not be served by the static file handler.

What am I doing wrong?

**Comment by brcontainer** [comment]
**1** - Please make sure the folder exists
**2** - I edited the code to check if the folder exists (recommend that you update), check the "console.log", try this:

``` javascript
html2canvas( [ document.body ], {
    "proxy":"html2canvasproxy.ashx",
    "logging":true,
    "onrendered": function(canvas) {
        var uridata = canvas.toDataURL("image/png");
        window.open(uridata);
    }
});
```

**3** - You added the `html2canvasproxy.ashx` in **JS** folder?
**4** - how are you using javascript?

**Comment by mandazi** [comment]
1 - Folder exists
2 - Updated to the latest code.
3 - It's in the JS folder
4 - I am using it identical to your example, except I am not getting the body.  I am getting a specific div and resizing it down to a smaller size for a thumbnail:

``` javascript
    html2canvas($(".view-container"), {
        //allowTaint: true,
        //useCORS: true,
        "logging": true,
        "proxy": "/js/html2canvasproxy.ashx",
        "onrendered": function (c) {
            // canvas is the final rendered <canvas> element
            var extra_canvas = document.createElement("canvas");
            extra_canvas.setAttribute('width', 128); //1024
            extra_canvas.setAttribute('height', 96); //768
            var ctx = extra_canvas.getContext('2d');
            ctx.drawImage(c, 0, 0, c.width, c.height, 0, 0, 128, 96); //1024,768
            var myImage = extra_canvas.toDataURL("image/png");

            window.open(myImage);
}
});
```

These are the logs I get:

> html2canvas: Preload starts: finding background-images
> html2canvas: Preload: Finding images
> html2canvas: Preload: Done.
> html2canvas: start: images: 1 / 3 (failed: 0)
> "NetworkError: 404 Not Found - http://MYSITEHERE/js/images/9198119e5333b5dcfcc353d3abb8eb1205c71e33"
> html2canvas: start: images: 2 / 3 (failed: 1)
> "NetworkError: 404 Not Found - http://MYSITEHERE/js/images/27a8b2a396fdae446d842f62bf9e4372784219da"
> html2canvas: start: images: 3 / 3 (failed: 2)
> Finished loading images: # 3 (failed: 2)
> html2canvas: Renderer: Canvas renderer done - returning canvas obj

The final rendered image is just a blank whitespace.  My guess it's not finding the image.  I checked the js/images folder and those files are there on the server but for whatever reason it still returns a 404.  Even when I go to it directly on the URL.

Note: MYSITEHERE replaced the real URL for privacy reasons.

**Comment by brcontainer** [comment]
I'm trying to simulate the error, but I can not, have an example online (on a server)?
Want very much help you with is the question.

Thanks again for sharing the problem.

**Comment by mandazi** [comment]
http://builder.fifthtribe.com/test/html2canvas.html

So I created a flat HTML test page with just the basic functionality of what I am trying to do.  When I did this, I no longer got the 404 or the failure logs.  The only issue now is that the image generated is blank and not the one I wanted with the batman image and the red circle.

I have included a link above that shows this.  The JS is at the bottom of the page.

**Comment by mandazi** [comment]
Hit the save button on the top left corner to run the code.

**Comment by brcontainer** [comment]
@mandazi I'm thinking that may be both, but to be sure I created a test file: https://github.com/brcontainer/html2canvas-csharp-proxy/blob/master/tests/testsever.ashx

Put in the same folder that is **"html2canvasproxy.ashx"** abrar and the following test:

http://builder.fifthtribe.com/js/testsever.ashx?url=https%3A%2F%2Fwww.google.com.br%2Fimages%2Fsrpr%2Flogo4w.png

After test, post the result here or let me know when you are available online.
Thanks.

**Comment by mandazi** [comment]
http://builder.fifthtribe.com/js/testsever.ashx?url=https%3A%2F%2Fwww.google.com.br%2Fimages%2Fsrpr%2Flogo4w.png

> url: "https://www.google.com.br/images/srpr/logo4w.png"
> realpath: "C:\Builder\js\images"
> realPathFile: "C:\Builder\js\images\8ba6f269d288c70cbae82bc09ce8d329a344807e"
> fullurl: "http://builder.fifthtribe.com/js/images/8ba6f269d288c70cbae82bc09ce8d329a344807e"

I am available online now.  How do you want to meet? Google+ or AIM or IRC?

**Comment by brcontainer** [comment]
https://plus.google.com/113007871188133084891/

18:00?

**Comment by mandazi** [comment]
I am in the US.  Eastern Standard Time.  18:00 is 6:00 PM, but is that EST?

**Comment by brcontainer** [comment]
For convenience, we will do so:
Here will be 3 hours will be available (from now on).

**Comment by mandazi** [comment]
I am messaging you on Google +.  Please respond.

**Comment by brcontainer** [comment]
Fixed https://github.com/brcontainer/html2canvas-csharp-proxy/commit/021b0dab7b3e32132302f0a542f45711b519f720

**Comment by mandazi** [comment]
Awesome!  Just to let you know the simple proxy script you wrote works now! Thanks a lot!

**Comment by Elgamal10** [comment]
" The only issue now is that the image generated is blank" , is there solution for this problem?

**Comment by brcontainer** [comment]
@Elgamal10 Put your code please (preferably in an online server)!

**[edit]**
@Elgamal10 Please if the problem persists, report it here or open a new "issue". I hope I can help.
